### ISSUE TITLE
Keep specified IP numbers

### ISSUE THREAD

**Issue by jbygdell** [NBISweden/rega-templates#4]
IP numbers that are DNS registered needs to be kept and reused for a deployments edge nodes.

DoD
There is a file that holds the reserved IPs
Specified IPs are not released back to the available IP pool on `terraform destroy`
Specified IPs are attached to edge nodes when instances are crated

**Comment by jonandernovella** [comment]
One solution for this is the following:
1) Manually request the allocation of the desired IPs at the Openstack project
2) Import the existing floating IP into Terraform  using ` terraform import openstack_compute_floatingip_v2.<resource_name> <floating-ip-id>`

This way, we can ensure that the ips we want are used, and not random ones.

**Comment by jonandernovella** [comment]
Another idea could be to do the following with the floating ip resource:

` lifecycle {
   prevent_destroy = true
 }` 

This would make sure that the resource does not get destroyed, and therefore Openstack will not release it from the allocated IPs list, and it will be also in the state.
